// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: storing_service.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StoringService_UploadTask_FullMethodName = "/storing.v1.StoringService/UploadTask"
	StoringService_GetTask_FullMethodName    = "/storing.v1.StoringService/GetTask"
)

// StoringServiceClient is the client API for StoringService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StoringServiceClient interface {
	UploadTask(ctx context.Context, in *UploadTaskRequest, opts ...grpc.CallOption) (*UploadTaskResponse, error)
	GetTask(ctx context.Context, in *GetTaskRequest, opts ...grpc.CallOption) (*GetTaskResponse, error)
}

type storingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStoringServiceClient(cc grpc.ClientConnInterface) StoringServiceClient {
	return &storingServiceClient{cc}
}

func (c *storingServiceClient) UploadTask(ctx context.Context, in *UploadTaskRequest, opts ...grpc.CallOption) (*UploadTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadTaskResponse)
	err := c.cc.Invoke(ctx, StoringService_UploadTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storingServiceClient) GetTask(ctx context.Context, in *GetTaskRequest, opts ...grpc.CallOption) (*GetTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTaskResponse)
	err := c.cc.Invoke(ctx, StoringService_GetTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StoringServiceServer is the server API for StoringService service.
// All implementations must embed UnimplementedStoringServiceServer
// for forward compatibility.
type StoringServiceServer interface {
	UploadTask(context.Context, *UploadTaskRequest) (*UploadTaskResponse, error)
	GetTask(context.Context, *GetTaskRequest) (*GetTaskResponse, error)
	mustEmbedUnimplementedStoringServiceServer()
}

// UnimplementedStoringServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStoringServiceServer struct{}

func (UnimplementedStoringServiceServer) UploadTask(context.Context, *UploadTaskRequest) (*UploadTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadTask not implemented")
}
func (UnimplementedStoringServiceServer) GetTask(context.Context, *GetTaskRequest) (*GetTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTask not implemented")
}
func (UnimplementedStoringServiceServer) mustEmbedUnimplementedStoringServiceServer() {}
func (UnimplementedStoringServiceServer) testEmbeddedByValue()                        {}

// UnsafeStoringServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StoringServiceServer will
// result in compilation errors.
type UnsafeStoringServiceServer interface {
	mustEmbedUnimplementedStoringServiceServer()
}

func RegisterStoringServiceServer(s grpc.ServiceRegistrar, srv StoringServiceServer) {
	// If the following call pancis, it indicates UnimplementedStoringServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StoringService_ServiceDesc, srv)
}

func _StoringService_UploadTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoringServiceServer).UploadTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoringService_UploadTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoringServiceServer).UploadTask(ctx, req.(*UploadTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoringService_GetTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoringServiceServer).GetTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StoringService_GetTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoringServiceServer).GetTask(ctx, req.(*GetTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StoringService_ServiceDesc is the grpc.ServiceDesc for StoringService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StoringService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "storing.v1.StoringService",
	HandlerType: (*StoringServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UploadTask",
			Handler:    _StoringService_UploadTask_Handler,
		},
		{
			MethodName: "GetTask",
			Handler:    _StoringService_GetTask_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "storing_service.proto",
}
