// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.31.1
// source: storing_service.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UploadTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	UploadedBy    string                 `protobuf:"bytes,2,opt,name=uploaded_by,json=uploadedBy,proto3" json:"uploaded_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadTaskRequest) Reset() {
	*x = UploadTaskRequest{}
	mi := &file_storing_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadTaskRequest) ProtoMessage() {}

func (x *UploadTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storing_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadTaskRequest.ProtoReflect.Descriptor instead.
func (*UploadTaskRequest) Descriptor() ([]byte, []int) {
	return file_storing_service_proto_rawDescGZIP(), []int{0}
}

func (x *UploadTaskRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *UploadTaskRequest) GetUploadedBy() string {
	if x != nil {
		return x.UploadedBy
	}
	return ""
}

type UploadTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	UploadUrl     string                 `protobuf:"bytes,2,opt,name=upload_url,json=uploadUrl,proto3" json:"upload_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadTaskResponse) Reset() {
	*x = UploadTaskResponse{}
	mi := &file_storing_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadTaskResponse) ProtoMessage() {}

func (x *UploadTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storing_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadTaskResponse.ProtoReflect.Descriptor instead.
func (*UploadTaskResponse) Descriptor() ([]byte, []int) {
	return file_storing_service_proto_rawDescGZIP(), []int{1}
}

func (x *UploadTaskResponse) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *UploadTaskResponse) GetUploadUrl() string {
	if x != nil {
		return x.UploadUrl
	}
	return ""
}

type GetTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskRequest) Reset() {
	*x = GetTaskRequest{}
	mi := &file_storing_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskRequest) ProtoMessage() {}

func (x *GetTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storing_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskRequest.ProtoReflect.Descriptor instead.
func (*GetTaskRequest) Descriptor() ([]byte, []int) {
	return file_storing_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetTaskRequest) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

type GetTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	UploadedBy    string                 `protobuf:"bytes,4,opt,name=uploaded_by,json=uploadedBy,proto3" json:"uploaded_by,omitempty"`
	UploadedAt    string                 `protobuf:"bytes,5,opt,name=uploaded_at,json=uploadedAt,proto3" json:"uploaded_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskResponse) Reset() {
	*x = GetTaskResponse{}
	mi := &file_storing_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskResponse) ProtoMessage() {}

func (x *GetTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storing_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskResponse.ProtoReflect.Descriptor instead.
func (*GetTaskResponse) Descriptor() ([]byte, []int) {
	return file_storing_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetTaskResponse) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *GetTaskResponse) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *GetTaskResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *GetTaskResponse) GetUploadedBy() string {
	if x != nil {
		return x.UploadedBy
	}
	return ""
}

func (x *GetTaskResponse) GetUploadedAt() string {
	if x != nil {
		return x.UploadedAt
	}
	return ""
}

var File_storing_service_proto protoreflect.FileDescriptor

const file_storing_service_proto_rawDesc = "" +
	"\n" +
	"\x15storing_service.proto\x12\n" +
	"storing.v1\"P\n" +
	"\x11UploadTaskRequest\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x1f\n" +
	"\vuploaded_by\x18\x02 \x01(\tR\n" +
	"uploadedBy\"L\n" +
	"\x12UploadTaskResponse\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12\x1d\n" +
	"\n" +
	"upload_url\x18\x02 \x01(\tR\tuploadUrl\")\n" +
	"\x0eGetTaskRequest\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\"\x9a\x01\n" +
	"\x0fGetTaskResponse\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12\x1f\n" +
	"\vuploaded_by\x18\x04 \x01(\tR\n" +
	"uploadedBy\x12\x1f\n" +
	"\vuploaded_at\x18\x05 \x01(\tR\n" +
	"uploadedAt2\xa1\x01\n" +
	"\x0eStoringService\x12K\n" +
	"\n" +
	"UploadTask\x12\x1d.storing.v1.UploadTaskRequest\x1a\x1e.storing.v1.UploadTaskResponse\x12B\n" +
	"\aGetTask\x12\x1a.storing.v1.GetTaskRequest\x1a\x1b.storing.v1.GetTaskResponseB\tZ\apkg/apib\x06proto3"

var (
	file_storing_service_proto_rawDescOnce sync.Once
	file_storing_service_proto_rawDescData []byte
)

func file_storing_service_proto_rawDescGZIP() []byte {
	file_storing_service_proto_rawDescOnce.Do(func() {
		file_storing_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_storing_service_proto_rawDesc), len(file_storing_service_proto_rawDesc)))
	})
	return file_storing_service_proto_rawDescData
}

var file_storing_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_storing_service_proto_goTypes = []any{
	(*UploadTaskRequest)(nil),  // 0: storing.v1.UploadTaskRequest
	(*UploadTaskResponse)(nil), // 1: storing.v1.UploadTaskResponse
	(*GetTaskRequest)(nil),     // 2: storing.v1.GetTaskRequest
	(*GetTaskResponse)(nil),    // 3: storing.v1.GetTaskResponse
}
var file_storing_service_proto_depIdxs = []int32{
	0, // 0: storing.v1.StoringService.UploadTask:input_type -> storing.v1.UploadTaskRequest
	2, // 1: storing.v1.StoringService.GetTask:input_type -> storing.v1.GetTaskRequest
	1, // 2: storing.v1.StoringService.UploadTask:output_type -> storing.v1.UploadTaskResponse
	3, // 3: storing.v1.StoringService.GetTask:output_type -> storing.v1.GetTaskResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_storing_service_proto_init() }
func file_storing_service_proto_init() {
	if File_storing_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_storing_service_proto_rawDesc), len(file_storing_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_storing_service_proto_goTypes,
		DependencyIndexes: file_storing_service_proto_depIdxs,
		MessageInfos:      file_storing_service_proto_msgTypes,
	}.Build()
	File_storing_service_proto = out.File
	file_storing_service_proto_goTypes = nil
	file_storing_service_proto_depIdxs = nil
}
