// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: api/analysis_service.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AnalyzeTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	ObjectKey     string                 `protobuf:"bytes,2,opt,name=object_key,json=objectKey,proto3" json:"object_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeTaskRequest) Reset() {
	*x = AnalyzeTaskRequest{}
	mi := &file_api_analysis_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeTaskRequest) ProtoMessage() {}

func (x *AnalyzeTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_analysis_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeTaskRequest.ProtoReflect.Descriptor instead.
func (*AnalyzeTaskRequest) Descriptor() ([]byte, []int) {
	return file_api_analysis_service_proto_rawDescGZIP(), []int{0}
}

func (x *AnalyzeTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *AnalyzeTaskRequest) GetObjectKey() string {
	if x != nil {
		return x.ObjectKey
	}
	return ""
}

type AnalyseTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyseTaskResponse) Reset() {
	*x = AnalyseTaskResponse{}
	mi := &file_api_analysis_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyseTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyseTaskResponse) ProtoMessage() {}

func (x *AnalyseTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_analysis_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyseTaskResponse.ProtoReflect.Descriptor instead.
func (*AnalyseTaskResponse) Descriptor() ([]byte, []int) {
	return file_api_analysis_service_proto_rawDescGZIP(), []int{1}
}

func (x *AnalyseTaskResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

type GetReportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetReportRequest) Reset() {
	*x = GetReportRequest{}
	mi := &file_api_analysis_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReportRequest) ProtoMessage() {}

func (x *GetReportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_analysis_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReportRequest.ProtoReflect.Descriptor instead.
func (*GetReportRequest) Descriptor() ([]byte, []int) {
	return file_api_analysis_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetReportRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type GetReportResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	TaskId               string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	IsPlagiarism         bool                   `protobuf:"varint,4,opt,name=is_plagiarism,json=isPlagiarism,proto3" json:"is_plagiarism,omitempty"`
	PlagiarismPercentage float32                `protobuf:"fixed32,5,opt,name=plagiarism_percentage,json=plagiarismPercentage,proto3" json:"plagiarism_percentage,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GetReportResponse) Reset() {
	*x = GetReportResponse{}
	mi := &file_api_analysis_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetReportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetReportResponse) ProtoMessage() {}

func (x *GetReportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_analysis_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetReportResponse.ProtoReflect.Descriptor instead.
func (*GetReportResponse) Descriptor() ([]byte, []int) {
	return file_api_analysis_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetReportResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *GetReportResponse) GetIsPlagiarism() bool {
	if x != nil {
		return x.IsPlagiarism
	}
	return false
}

func (x *GetReportResponse) GetPlagiarismPercentage() float32 {
	if x != nil {
		return x.PlagiarismPercentage
	}
	return 0
}

type GenerateWordCloudRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileContent   []byte                 `protobuf:"bytes,1,opt,name=file_content,json=fileContent,proto3" json:"file_content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateWordCloudRequest) Reset() {
	*x = GenerateWordCloudRequest{}
	mi := &file_api_analysis_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateWordCloudRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateWordCloudRequest) ProtoMessage() {}

func (x *GenerateWordCloudRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_analysis_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateWordCloudRequest.ProtoReflect.Descriptor instead.
func (*GenerateWordCloudRequest) Descriptor() ([]byte, []int) {
	return file_api_analysis_service_proto_rawDescGZIP(), []int{4}
}

func (x *GenerateWordCloudRequest) GetFileContent() []byte {
	if x != nil {
		return x.FileContent
	}
	return nil
}

type GenerateWordCloudResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageUrl      string                 `protobuf:"bytes,1,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateWordCloudResponse) Reset() {
	*x = GenerateWordCloudResponse{}
	mi := &file_api_analysis_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateWordCloudResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateWordCloudResponse) ProtoMessage() {}

func (x *GenerateWordCloudResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_analysis_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateWordCloudResponse.ProtoReflect.Descriptor instead.
func (*GenerateWordCloudResponse) Descriptor() ([]byte, []int) {
	return file_api_analysis_service_proto_rawDescGZIP(), []int{5}
}

func (x *GenerateWordCloudResponse) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

var File_api_analysis_service_proto protoreflect.FileDescriptor

const file_api_analysis_service_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/analysis_service.proto\x12\vanalysis.v1\"L\n" +
	"\x12AnalyzeTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1d\n" +
	"\n" +
	"object_key\x18\x02 \x01(\tR\tobjectKey\"-\n" +
	"\x13AnalyseTaskResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status\"+\n" +
	"\x10GetReportRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"\x86\x01\n" +
	"\x11GetReportResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12#\n" +
	"\ris_plagiarism\x18\x04 \x01(\bR\fisPlagiarism\x123\n" +
	"\x15plagiarism_percentage\x18\x05 \x01(\x02R\x14plagiarismPercentage\"=\n" +
	"\x18GenerateWordCloudRequest\x12!\n" +
	"\ffile_content\x18\x01 \x01(\fR\vfileContent\"8\n" +
	"\x19GenerateWordCloudResponse\x12\x1b\n" +
	"\timage_url\x18\x01 \x01(\tR\bimageUrl2\x93\x02\n" +
	"\x0fAnalysisService\x12P\n" +
	"\vAnalyseTask\x12\x1f.analysis.v1.AnalyzeTaskRequest\x1a .analysis.v1.AnalyseTaskResponse\x12J\n" +
	"\tGetReport\x12\x1d.analysis.v1.GetReportRequest\x1a\x1e.analysis.v1.GetReportResponse\x12b\n" +
	"\x11GenerateWordCloud\x12%.analysis.v1.GenerateWordCloudRequest\x1a&.analysis.v1.GenerateWordCloudResponseB\tZ\apkg/apib\x06proto3"

var (
	file_api_analysis_service_proto_rawDescOnce sync.Once
	file_api_analysis_service_proto_rawDescData []byte
)

func file_api_analysis_service_proto_rawDescGZIP() []byte {
	file_api_analysis_service_proto_rawDescOnce.Do(func() {
		file_api_analysis_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_analysis_service_proto_rawDesc), len(file_api_analysis_service_proto_rawDesc)))
	})
	return file_api_analysis_service_proto_rawDescData
}

var file_api_analysis_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_analysis_service_proto_goTypes = []any{
	(*AnalyzeTaskRequest)(nil),        // 0: analysis.v1.AnalyzeTaskRequest
	(*AnalyseTaskResponse)(nil),       // 1: analysis.v1.AnalyseTaskResponse
	(*GetReportRequest)(nil),          // 2: analysis.v1.GetReportRequest
	(*GetReportResponse)(nil),         // 3: analysis.v1.GetReportResponse
	(*GenerateWordCloudRequest)(nil),  // 4: analysis.v1.GenerateWordCloudRequest
	(*GenerateWordCloudResponse)(nil), // 5: analysis.v1.GenerateWordCloudResponse
}
var file_api_analysis_service_proto_depIdxs = []int32{
	0, // 0: analysis.v1.AnalysisService.AnalyseTask:input_type -> analysis.v1.AnalyzeTaskRequest
	2, // 1: analysis.v1.AnalysisService.GetReport:input_type -> analysis.v1.GetReportRequest
	4, // 2: analysis.v1.AnalysisService.GenerateWordCloud:input_type -> analysis.v1.GenerateWordCloudRequest
	1, // 3: analysis.v1.AnalysisService.AnalyseTask:output_type -> analysis.v1.AnalyseTaskResponse
	3, // 4: analysis.v1.AnalysisService.GetReport:output_type -> analysis.v1.GetReportResponse
	5, // 5: analysis.v1.AnalysisService.GenerateWordCloud:output_type -> analysis.v1.GenerateWordCloudResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_analysis_service_proto_init() }
func file_api_analysis_service_proto_init() {
	if File_api_analysis_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_analysis_service_proto_rawDesc), len(file_api_analysis_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_analysis_service_proto_goTypes,
		DependencyIndexes: file_api_analysis_service_proto_depIdxs,
		MessageInfos:      file_api_analysis_service_proto_msgTypes,
	}.Build()
	File_api_analysis_service_proto = out.File
	file_api_analysis_service_proto_goTypes = nil
	file_api_analysis_service_proto_depIdxs = nil
}
